name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-networking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test both platform packages
        run: yarn test
